services:
  ktor:
    build: .
    container_name: ktor
    image: mivdev/program-cloud-ktor
    user: root
    volumes:
      - ktor-media:/data/files
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USERNAME=ktor
      - DB_PASSWORD=GqNvKyF8
      - DB_URL=jdbc:postgresql://db:5432/program_cloud_db
    
  db:
    image: postgres
    environment:
      POSTGRES_DB: program_cloud_db
      POSTGRES_USER: ktor
      POSTGRES_PASSWORD: GqNvKyF8
    container_name: db
    ports:
      - "54333:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
volumes:
  ktor-media: {}
  pg-data: {}
